main:
  push:
    - services:
        - docker # 声明后，流水线内可以直接使用docker命令
      stages:
        - name: set docker tag
          script: echo -n "${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest"
          exports:
            info: IMAGE_TAG

        - name: docker build
          script: docker build -t $IMAGE_TAG .

        - name: push image
          script: docker push $IMAGE_TAG
