allowBuilds:
  esbuild: true
  protobufjs: true
  sharp: true
minimumReleaseAge: 0
shellEmulator: true

trustPolicy: no-downgrade
packages:
  - apps/frontend
  - apps/backend
  - apps/shared
  - apps/auth
  - apps/auth/panel
